"""
Variation strategy metadata and helpers.
The actual variation content is generated by Claude; this module provides
the structural intent so generate.py can format consistent output.
"""
from dataclasses import dataclass
from typing import List, Dict, Any


@dataclass
class VariationInfo:
    id: int
    name: str
    character: str
    tempo: int
    note_count: int


def extract_variation_info(variation: Dict[str, Any]) -> VariationInfo:
    notes = variation.get("notes", [])
    return VariationInfo(
        id=variation.get("id", 0),
        name=variation.get("name", f"Variation {variation.get('id', '?')}"),
        character=variation.get("character", ""),
        tempo=variation.get("tempo", 120),
        note_count=len(notes),
    )


_EXPRESSIVE_FIELDS = ("bend_start", "bend_end", "vibrato", "vibrato_delay")


def _note_to_dict(note: Any) -> Dict[str, Any]:
    """Accept either a compact [pitch, duration, velocity, time] array
    (the cost-optimized format Claude now emits) or the legacy
    {pitch, duration, velocity, time, ...} dict and return the dict form."""
    if isinstance(note, list) and len(note) >= 4:
        return {
            "pitch": note[0],
            "duration": note[1],
            "velocity": note[2],
            "time": note[3],
        }
    return note if isinstance(note, dict) else {}


def validate_variation(variation: Dict[str, Any]) -> List[str]:
    """Return a list of warning strings for a variation. Empty = valid."""
    warnings = []
    notes = variation.get("notes", [])

    if not notes:
        warnings.append("no notes in variation")
        return warnings

    for i, raw in enumerate(notes):
        note = _note_to_dict(raw)
        pitch = note.get("pitch", -1)
        if not (0 <= pitch <= 127):
            warnings.append(f"note {i}: pitch {pitch} out of range [0,127]")

        velocity = note.get("velocity", -1)
        if not (1 <= velocity <= 127):
            warnings.append(f"note {i}: velocity {velocity} out of range [1,127]")

        duration = note.get("duration", 0)
        if duration <= 0:
            warnings.append(f"note {i}: duration {duration} must be > 0")

        time = note.get("time", -1)
        if time < 0:
            warnings.append(f"note {i}: time {time} must be >= 0")

    return warnings


def sanitize_variation(variation: Dict[str, Any]) -> Dict[str, Any]:
    """Clamp note values to valid MIDI ranges. Accepts compact array notes."""
    notes = variation.get("notes", [])
    clean_notes = []
    for raw in notes:
        note = _note_to_dict(raw)
        clean = {
            "pitch": max(0, min(127, int(note.get("pitch", 60)))),
            "velocity": max(1, min(127, int(note.get("velocity", 80)))),
            "duration": max(0.01, float(note.get("duration", 0.5))),
            "time": max(0.0, float(note.get("time", 0.0))),
        }
        for field in _EXPRESSIVE_FIELDS:
            if field in note:
                clean[field] = note[field]
        clean_notes.append(clean)
    return {**variation, "notes": clean_notes}
